### PR TITLE
Conner/registration v2

### PR DESCRIPTION
**Pull request by cchyung**
Revamp registration flow with new progress bar

Couldn't use context because of gatbsy layout

### CODE REVIEW

**Comment by Tony1023** [comment]
@cchyung Looks like deployment failed.

I haven't gone thru the code tho - will do that later

**Comment by cchyung** [comment]
@Tony1023 re pushed the fix

**Review by Tony1023 — APPROVED** [review]
Both code & view look great lol - but do we wanna retain the info on the previous page when we hit back button? It did not retain on my end I'm not sure if it's because of my shitty internet

**Comment by cchyung** [comment]
> Both code & view look great lol - but do we wanna retain the info on the previous page when we hit back button? It did not retain on my end I'm not sure if it's because of my shitty internet

hm this is true - maybe I'll save this info on local storage instead of passing it along the navigation stack.

**Comment by Tony1023** [comment]
> > Both code & view look great lol - but do we wanna retain the info on the previous page when we hit back button? It did not retain on my end I'm not sure if it's because of my shitty internet
> 
> hm this is true - maybe I'll save this info on local storage instead of passing it along the navigation stack.

Was it in RegistrationContext?

**Pull request merged**
